name: Build Windows

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build
        run: |
          pyinstaller --onefile --windowed -n RPGMVMZLinuxConverter --add-data "src/style.qss;." src/main.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: RPGMakerConverter-Windows
          path: dist/*.exe
